export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_CLIENTS = "UPDATE_CLIENTS";
